apiVersion: v1
kind: Namespace
metadata:
  name: private-km
  labels:
    app.kubernetes.io/name: private-km
    # Huawei CCE uses this label for network policy enforcement
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
